# Generated by Django 4.2.1 on 2023-06-04 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(unique=True)),
                ('device_id', models.CharField(default=None, null=True)),
                ('ip_address', models.GenericIPAddressField(default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expired_at', models.DateTimeField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
