# Generated by Django 4.1.3 on 2023-07-08 16:05

from django.db import migrations, models


# generates username for previous records
def generate_username(apps, schema_editor):
    MetaDataValue = apps.get_model('authentication', 'user')
    db_alias = schema_editor.connection.alias
    from django.db.models import F, Value, functions, CharField
    MetaDataValue.objects.using(db_alias).all().update(
        username=functions.Concat(F('email'), Value("_"), F('role'), output_field=CharField())
    )

def reverse_generate_username(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(
            generate_username, reverse_generate_username
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, unique=True),
        )
    ]
