# Generated by Django 4.1.3 on 2023-10-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_country_user_username'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email_per_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
