# Generated by Django 4.1.3 on 2023-09-10 13:11

import activity.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(null=True)),
                ('activity_type', models.CharField(max_length=20)),
                ('content_type', models.CharField(max_length=20, null=True, validators=[activity.models.validation_content_type])),
                ('content_id', models.PositiveIntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'activity_log',
                'verbose_name_plural': 'activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['activity_type'], name='activity_log_activity_type_idx'),
        ),
    ]
