# Generated by Django 4.1.3 on 2023-07-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
