# Generated by Django 4.1.3 on 2023-07-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0002_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
