# Generated by Django 4.1.3 on 2023-08-21 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediacontent', '0003_podcastseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('audio_metadata', models.JSONField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('episode_no', models.IntegerField(default=1)),
                ('duration_in_sec', models.IntegerField(default=0)),
                ('covers', models.JSONField(null=True)),
                ('language', models.CharField(db_index=True, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='mediacontent.category')),
                ('featured_artists', models.ManyToManyField(related_name='featured_artists', to=settings.AUTH_USER_MODEL)),
                ('podcast_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediacontent.podcastseries')),
                ('tags', models.ManyToManyField(to='mediacontent.tag')),
            ],
            options={
                'verbose_name': 'podcast_episode',
                'verbose_name_plural': 'podcast_episodes',
            },
        ),
        migrations.AddConstraint(
            model_name='podcastepisode',
            constraint=models.UniqueConstraint(fields=('podcast_series', 'title'), name='unique_podcast_series_episode_idx', violation_error_message='Title should be unique for a series'),
        ),
    ]
