# Generated by Django 4.1.3 on 2023-08-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0005_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='episode_no',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
