# Generated by Django 4.1.3 on 2023-08-05 11:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mediacontent.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mediacontent', '0005_podcastseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=mediacontent.models.cover_upload_dir)),
                ('bg_color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Field must contain only letters and numbers.', regex='^#([A-Fa-f0-9]{6})$')])),
                ('dim', models.CharField(choices=[('LARGE', '640px'), ('MEDIUM', '320px'), ('THUMB', '64px'), ('ORIGINAL', '')], max_length=20)),
                ('height', models.SmallIntegerField(default=0)),
                ('width', models.SmallIntegerField(default=0)),
                ('object_id', models.BigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'cover',
                'verbose_name_plural': 'covers',
            },
        ),
        migrations.AddIndex(
            model_name='cover',
            index=models.Index(fields=['content_type', 'object_id'], name='mediaconten_content_271d70_idx'),
        ),
    ]
