# Generated by Django 4.1.3 on 2023-08-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0006_alter_podcastepisode_episode_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='play_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
