# Generated by Django 4.1.3 on 2023-08-05 11:34

from django.db import migrations, models
import django.db.models.deletion
import mediacontent.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mediacontent', '0006_cover_cover_mediaconten_content_271d70_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=mediacontent.models.audio_upload_dir)),
                ('bit_rate', models.SmallIntegerField(choices=[(32, '32 Kbps'), (64, '64 Kbps'), (128, '128 Kbps')])),
                ('format', models.CharField(default='', max_length=5)),
                ('object_id', models.BigIntegerField()),
                ('size_in_kb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'audio',
                'verbose_name_plural': 'audios',
            },
        ),
        migrations.AddIndex(
            model_name='audio',
            index=models.Index(fields=['content_type', 'object_id'], name='mediaconten_content_7b8684_idx'),
        ),
    ]
