# Generated by Django 4.1.3 on 2023-09-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0007_podcastepisode_play_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastepisode',
            name='categories',
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='episode_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='language',
            field=models.CharField(max_length=3),
        ),
        migrations.RemoveField(
            model_name='podcastepisode',
            name='tags',
        ),
        migrations.AddIndex(
            model_name='podcastepisode',
            index=models.Index(fields=['language'], name='idx_ps_language'),
        ),
        migrations.AddIndex(
            model_name='podcastepisode',
            index=models.Index(condition=models.Q(('published', True)), fields=['podcast_series', 'episode_no'], name='partial_idx_series_episode'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='categories',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='tags',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
