# Generated by Django 4.1.3 on 2023-08-06 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediacontent', '0007_audio_audio_mediaconten_content_7b8684_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('duration_in_sec', models.IntegerField(default=0)),
                ('language', models.CharField(db_index=True, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'podcast_episode',
                'verbose_name_plural': 'podcast_episodes',
            },
        ),
        migrations.AlterField(
            model_name='audio',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_name_category'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_name_tag'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='categories',
            field=models.ManyToManyField(to='mediacontent.category'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='featured_artists',
            field=models.ManyToManyField(null=True, related_name='featured_artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='podcast_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediacontent.podcastseries'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='tags',
            field=models.ManyToManyField(null=True, to='mediacontent.tag'),
        ),
    ]
