# Generated by Django 4.1.3 on 2023-09-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0008_remove_podcastepisode_categories_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='podcastepisode',
            name='idx_ps_language',
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='slug',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX podcastepisode_title_trigram_idx ON mediacontent_podcastepisode USING gin(title gin_trgm_ops) where published;",
            reverse_sql="DROP INDEX IF EXISTS podcastepisode_title_trigram_idx;"
        )
    ]
