# Generated by Django 4.1.3 on 2023-08-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0008_podcastepisode_alter_audio_id_alter_tag_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='podcastepisode',
            constraint=models.UniqueConstraint(fields=('podcast_series', 'title'), name='unique_podcast_series_episode_idx', violation_error_message='Title should be unique for a series'),
        ),
    ]
