# Generated by Django 4.1.3 on 2023-08-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0009_podcastepisode_unique_podcast_series_episode_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='dim',
            field=models.CharField(choices=[('LARGE', '320px'), ('MEDIUM', '160px'), ('THUMB', '64px'), ('ORIGINAL', '')], max_length=20),
        ),
    ]
