# Generated by Django 4.1.3 on 2023-09-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0009_remove_podcastepisode_idx_ps_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bg_color',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
