# Generated by Django 4.1.3 on 2023-08-10 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediacontent', '0011_alter_audio_content_type_alter_audio_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcastseries',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='featured_artists',
            field=models.ManyToManyField(related_name='featured_artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='tags',
            field=models.ManyToManyField(to='mediacontent.tag'),
        ),
    ]
