# Generated by Django 4.1.3 on 2023-08-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0012_podcastepisode_published_podcastseries_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('item_count', models.IntegerField(default=0)),
                ('contents', models.JSONField(blank=True, null=True)),
                ('section_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
