# Generated by Django 4.1.3 on 2023-08-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0013_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcastseries',
            name='slug',
            field=models.SlugField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
