# Generated by Django 4.1.3 on 2023-08-16 04:53

from django.db import migrations, models


def add_published_at_to_episodes(apps, schema_editor):
    MetaDataValue = apps.get_model('mediacontent', 'podcastepisode')
    db_alias = schema_editor.connection.alias
    from django.db.models import F, Value, functions, DateTimeField
    MetaDataValue.objects.using(db_alias).filter(published=True).update(
        published_at=functions.datetime.datetime.utcnow()
    )


def remove_published_at_from_episode(apps, schema_editor):
    pass


def add_published_at_to_series(apps, schema_editor):
    MetaDataValue = apps.get_model('mediacontent', 'podcastseries')
    db_alias = schema_editor.connection.alias
    from django.db.models import F, Value, functions, CharField
    MetaDataValue.objects.using(db_alias).filter(published=True).update(
        published_at=functions.datetime.datetime.utcnow()
    )


def remove_published_at_from_series(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0014_podcastepisode_slug_podcastseries_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            add_published_at_to_episodes, remove_published_at_from_episode
        ),
        migrations.AddField(
            model_name='podcastseries',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            add_published_at_to_series, remove_published_at_from_series
        ),
    ]
