# Generated by Django 4.1.3 on 2023-08-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0015_podcastepisode_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='serial_no',
            field=models.IntegerField(default=1),
        ),
    ]
