# Generated by Django 4.1.3 on 2023-09-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercollection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
