# Generated by Django 4.1.3 on 2024-01-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercollection', '0002_playlist_is_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='total_duration_sec',
        ),
    ]
